server:
  port: 8088

student:
#  name: zs
#  age: 23
  sex: true
  birthday: 2019/02/12
  location:
    province: 陕西1
    city: 西安1
    zone: 莲湖区1
#  {province: "陕\n西", city: '西\n安', zone: 莲湖\n区} 行内写法
  hobbies: [足球，篮球] # 行内写法
#    - 足球
#    - 篮球
  skills: [编程，金融] # 行内写法
#    - 编程
#    - 金融
  pet: {nickName: wc11, strain: hsq}
#    nickName: wc
#    strain: hsq