server:
  port: 8088

student:
  name: zs
  age: 23
  sex: true
  birthday: 2019/02/12
  location: {province: 陕西, city: 西安, zone: 莲湖区}
  hobbies:
    - 足球
    - 篮球
  skills:
    - 编程
    - 金融
  pet:
    nickName: wc
    strain: hsq